spring:
  config:
    import: ""
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "${BACKEND_URL}/login/oauth2/code/google"
  session:
    cookie:
      same-site: none
      secure: true

server:
  forward-headers-strategy: framework
