spring:
  config:
    import: "optional:application-secrets.yml"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 24h
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

server:
  port: 8080

logging:
  level:
    root: WARN
    com.example.demo: INFO
    org.springframework.web.servlet.DispatcherServlet: WARN
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss z} %highlight(%-5level) %cyan(%logger{25}) - %msg%n"
